### ISSUE TITLE
Persona images not working in Sketch version 41.2 (35397)

### ISSUE THREAD

**Issue by mediter** [timuric/Content-generator-sketch-plugin#147]
just re-downloaded the zip of the current master branch of Content Generator repo.

Using any of the three options in the Persona images produce no change. the system show the following relevant log.

```
Male (Sketch Plugin)[4807]: ~/Dropbox/Sketch3/Plugins/Content Generator%20Sketch%20Plugin/CG.sketchplugin/Contents/Sketch/data/images/persona/male/

Sketch[4807]: Exception: TypeError: null is not an object (evaluating 'imagesFileNames. count')

Male (Sketch Plugin)[4807]: TypeError: null is not an object (evaluating 'imagesFileNames. count')
	sourceURL: ~/Dropbox/Sketch3/Plugins/Content Generator Sketch Plugin/CG.sketchplugin/Contents/Sketch/Persona/Photos/Male.js
```

a bit explanation about the location of Sketch plug-in folder:

I used "ln -s" command to create a symlink so that the plugins can be synced to the cloud, that way I don't have reinstall them manually after OS reinstallation.

All the other plug-ins are working, so I assume this might not be the cause.

Thank you for the awesome plug-in!

**Comment by rockallite** [comment]
Did you installed the plugin via Sketch Toolbox? It doesn't work that way. I've tried that.

Instead, I uninstalled it from Sketch Toolbox, then followed the [official instructions](https://github.com/timuric/Content-generator-sketch-plugin#installation) to re-install it.

And now it works.

**Comment by mediter** [comment]
first installed via Sketch Toolbox, didn't work.

Removed. Downloaded zip file of the current master branch. Manually put the files inside Sketch's plug-in folder. Still didn't work.

**Comment by alexblakwolf** [comment]
@rockallite Works Now 💃🏻
Thanks!!

**Comment by skondris** [comment]
These aren't working for me either. Just stopped working a while back. I've uninstalled/ reinstalled, etc and I can get the flickr images to load in but nothing under persona.... anyone else having this issue?

**Comment by jayechau** [comment]
@alexblakwolf still didn't work T-T

**Comment by RobSwish** [comment]
Would really really love this to be fixed please guys.

**Comment by alexhitch** [comment]
For those who installed from Sketch Toolbox. Uninstall the plugin in Sketch Toolbox. Follow the [instraction](https://github.com/timuric/Content-generator-sketch-plugin#installation). It worked for me. Thanks!

**Comment by skondris** [comment]
@alexhitch what specifically worked for you? The rest of the plugin works fine, yes. but the "Persona>Photos>Female/Male/Neutral" image generation does NOT work in Sketch 42.

**Comment by skondris** [comment]
@timuric you closed a duplicate of this issue, but I cannot get this to work even in the latest build from March 6, 2017. please advise.

**Comment by skondris** [comment]
This has been fixed! I've verified that it works now as of the March 6, 2017 build. Thank you @timuric !

**Comment by wootlebug** [comment]
I've installed through the Sketch Toolbox, I've installed manually.  I have the latest version of sketch and content generator plug in and I still don't get persona images.  Any suggestions?
