### ISSUE TITLE
Add Rad Faces?

### ISSUE THREAD

**Issue by robscherer** [timuric/Content-generator-sketch-plugin#86]
http://www.radfaces.com/

**Comment by timuric** [comment]
@robscherer have fun https://github.com/timuric/Content-generator-sketch-plugin/releases

**Comment by robscherer** [comment]
:-)

Not working for me though (soz, I’m a bit “code challenged”) - assume it needs to be .sketchpluginerized?

**Comment by timuric** [comment]
ups, thanks! it is fixed now

**Comment by robscherer** [comment]
Hmm, still not working for me. Doesn’t populate shapes. No error message.

**Comment by timuric** [comment]
@robscherer I should have tested it better. Please update, should work now. Thanks for the feedback!

**Comment by robscherer** [comment]
Getting there. I hope you don’t feel like I’m a picky product owner ;-) but… images aren’t resizing the way others do. Rad faces below and female persona below that to illustrate: (anything that can be done?)

[cid:C2696E74-C5B9-46AE-888A-74E665BBF0AA]

[cid:7356F9CC-FC19-43F7-8DF4-30825A6681C8]

**Comment by timuric** [comment]
@robscherer not picky at all, I appreciate your feedback. Please update ;)

**Comment by robscherer** [comment]
Perfect!

:-)
